version: 2.0

templates:
  checkout_cache_key: &checkout_cache_key
    v1-repo-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:stretch-scm
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: *checkout_cache_key
          paths:
            - ~/repo

  build:node-8:
    docker:
      - image: circleci/node:8.15.0-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-8.15.0-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --pure-lock-file
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-8.15.0-{{ checksum "yarn.lock" }}

  build:node-9:
    docker:
      - image: circleci/node:9.11.2-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-9.11.2-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --pure-lock-file
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-9.11.2-{{ checksum "yarn.lock" }}

  build:node-10:
    docker:
      - image: circleci/node:10.15.1-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-10.15.1-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --pure-lock-file
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-10.15.1-{{ checksum "yarn.lock" }}

  test:node-8:
    docker:
      - image: circleci/node:8.15.0-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-8.15.0-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test:node-9:
    docker:
      - image: circleci/node:9.11.2-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-9.11.2-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test:node-10:
    docker:
      - image: circleci/node:10.15.1-stretch
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: *checkout_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-node-10.15.1-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - build:node-8:
          requires:
            - checkout_code
      - build:node-9:
          requires:
            - checkout_code
      - build:node-10:
          requires:
            - checkout_code
      - test:node-8:
          requires:
            - build:node-8
      - test:node-9:
          requires:
            - build:node-9
      - test:node-10:
          requires:
            - build:node-10
